# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: ArctosDB Documentation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "documentation-wiki" # the subpath of your site, e.g. /blog
cover: ""
logo: ""

#url: "http://docs.arctosdb.org" # the base hostname & protocol for your site
url: "https://arctos.github.io"
twitter_username: arctosdb
github_username:  Arctos

# Build settings
markdown: kramdown
markdown_ext: "markdown, mkdown, mkdn, mkd, md"
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
paginate: 5
paginate_path: "/page:num/"
